-- GENERATED by scripts/seed-personas.ts from evals/personas.ts. Do not edit.
--
-- #269 — one persona per role, for the browser suite and the screenshot
-- matrix. LOCAL ONLY: scripts/seed-personas.ts --apply refuses any host that
-- is not local, and the password is a local test value.
--
-- PRIVILEGED, like every seed here (supabase/seeds/README.md): it writes as
-- postgres, through no handler. It shows what each role SEES; it proves
-- nothing about what a handler WRITES.
--
-- Join approval is not built, so `member` and `applicant` differ only in
-- group_memberships.confirmed_at. Products and services sit on the business
-- Page only: an item's own page resolves under a business Page or under its
-- poster, never under another kind of Page.

begin;
set local eval.skip_signup_hook = 'on';

-- 1. People.
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000001', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-stranger@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-000000000001', '{"sub":"0a000000-0000-4000-8000-000000000001","email":"qa-stranger@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000001', 'qa-stranger', 'QA Stranger', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000001', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000001' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000002', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-follower@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000002', '0a000000-0000-4000-8000-000000000002', '0a000000-0000-4000-8000-000000000002', '{"sub":"0a000000-0000-4000-8000-000000000002","email":"qa-follower@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000002', 'qa-follower', 'QA Follower', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000002', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000002' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000003', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-member@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000003', '0a000000-0000-4000-8000-000000000003', '0a000000-0000-4000-8000-000000000003', '{"sub":"0a000000-0000-4000-8000-000000000003","email":"qa-member@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000003', 'qa-member', 'QA Member', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000003', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000003' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000004', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-applicant@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-000000000004', '{"sub":"0a000000-0000-4000-8000-000000000004","email":"qa-applicant@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000004', 'qa-applicant', 'QA Applicant', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000004', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000004' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000005', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-rsvp@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-000000000005', '{"sub":"0a000000-0000-4000-8000-000000000005","email":"qa-rsvp@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000005', 'qa-rsvp', 'QA Rsvp', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000005', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000005' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000006', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-operator@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000006', '0a000000-0000-4000-8000-000000000006', '0a000000-0000-4000-8000-000000000006', '{"sub":"0a000000-0000-4000-8000-000000000006","email":"qa-operator@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000006', 'qa-operator', 'QA Operator', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000006', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000006' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000011', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-ownerbusiness@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000011', '0a000000-0000-4000-8000-000000000011', '0a000000-0000-4000-8000-000000000011', '{"sub":"0a000000-0000-4000-8000-000000000011","email":"qa-ownerbusiness@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000011', 'qa-owner-business', 'QA Owner Business', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000011', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000011' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000012', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-ownerplace@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000012', '0a000000-0000-4000-8000-000000000012', '0a000000-0000-4000-8000-000000000012', '{"sub":"0a000000-0000-4000-8000-000000000012","email":"qa-ownerplace@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000012', 'qa-owner-place', 'QA Owner Place', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000012', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000012' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000013', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-ownerinterest@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000013', '0a000000-0000-4000-8000-000000000013', '0a000000-0000-4000-8000-000000000013', '{"sub":"0a000000-0000-4000-8000-000000000013","email":"qa-ownerinterest@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000013', 'qa-owner-interest', 'QA Owner Interest', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000013', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000013' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000014', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-ownerpractice@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000014', '0a000000-0000-4000-8000-000000000014', '0a000000-0000-4000-8000-000000000014', '{"sub":"0a000000-0000-4000-8000-000000000014","email":"qa-ownerpractice@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000014', 'qa-owner-practice', 'QA Owner Practice', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000014', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000014' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000015', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-ownerevent@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000015', '0a000000-0000-4000-8000-000000000015', '0a000000-0000-4000-8000-000000000015', '{"sub":"0a000000-0000-4000-8000-000000000015","email":"qa-ownerevent@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000015', 'qa-owner-event', 'QA Owner Event', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000015', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000015' and scope_kind = 'primary_home');
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values ('0a000000-0000-4000-8000-000000000016', '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', 'qa-ownerfamily@example.test',
  extensions.crypt('qa-persona-local-only', extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values ('0a000000-0000-4000-8000-000000000016', '0a000000-0000-4000-8000-000000000016', '0a000000-0000-4000-8000-000000000016', '{"sub":"0a000000-0000-4000-8000-000000000016","email":"qa-ownerfamily@example.test","email_verified":true}',
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values ('0a000000-0000-4000-8000-000000000016', 'qa-owner-family', 'QA Owner Family', 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select '0a000000-0000-4000-8000-000000000016', (select id from public.places where slug = 'oak-park' limit 1), 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = '0a000000-0000-4000-8000-000000000016' and scope_kind = 'primary_home');

-- 2. A Page of every kind, its place, and the people around it.
insert into public.locations (id, member_id, kind, label, slug, geography, place_id, discoverability)
values ('0c000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-000000000011', 'permanent', 'QA Corner Bakery, main spot', 'qa-corner-bakery-shop',
  ST_GeogFromText('POINT(-121.4700 38.5410)'), (select id from public.places where slug = 'oak-park' limit 1), 'listed')
on conflict (id) do nothing;
insert into public.groups (id, kind, purpose, name, slug, public_id, description, lifecycle_state, discoverability, founder_member_id, anchor_location_id)
values ('0b000000-0000-4000-8000-000000000001', 'business', 'sell', 'QA Corner Bakery', 'qa-corner-bakery', 'qa0b01',
  'A seeded business Page for the browser suite.', 'active', 'listed', '0a000000-0000-4000-8000-000000000011', '0c000000-0000-4000-8000-000000000001')
on conflict (id) do nothing;
update public.groups set discoverability = 'listed' where id = '0b000000-0000-4000-8000-000000000001';
insert into public.group_businesses (group_id, display_name, public_description)
values ('0b000000-0000-4000-8000-000000000001', 'QA Corner Bakery', 'Bread and pastries, baked in Oak Park.') on conflict do nothing;
insert into public.group_memberships (group_id, member_id, role, source, relationship, confirmed_by_member_id, confirmed_at) values
  ('0b000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-000000000011', 'owner', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-000000000003', 'member', 'explicit', 'member', '0a000000-0000-4000-8000-000000000011', now()),
  ('0b000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-000000000004', 'member', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000001', '0a000000-0000-4000-8000-000000000002', 'member', 'soft_via_follow', 'follower', null, null)
on conflict (group_id, member_id) do nothing;
insert into public.page_posts (id, group_id, body, starts_at, location_id, lifecycle_state, discoverability) values
  ('0e000000-0000-4000-8000-000000000101', '0b000000-0000-4000-8000-000000000001', 'Saturday at QA Corner Bakery: come along.', date_trunc('day', now()) + interval '3 days 17 hours', '0c000000-0000-4000-8000-000000000001', 'active', 'listed'),
  ('0e000000-0000-4000-8000-000000000102', '0b000000-0000-4000-8000-000000000001', 'Thanks to everyone who came last week.', null, null, 'active', 'listed')
on conflict (id) do nothing;
insert into public.items (id, member_id, kind, title, description, state, group_id)
values ('0d000000-0000-4000-8000-000000000101', '0a000000-0000-4000-8000-000000000011', 'gathering', 'QA Corner Bakery meetup', 'Come along.', 'published', '0b000000-0000-4000-8000-000000000001')
on conflict (id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values ('0d000000-0000-4000-8000-000000000101', date_trunc('day', now()) + interval '5 days 18 hours')
on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select '0d000000-0000-4000-8000-000000000101', '0c000000-0000-4000-8000-000000000001', 'one_time', 'approved'
 where not exists (select 1 from public.item_locations where item_id = '0d000000-0000-4000-8000-000000000101');
insert into public.item_responses (item_id, responder_member_id, response_kind)
select v.item, v.who, 'rsvp' from (values ('0d000000-0000-4000-8000-000000000101'::uuid, '0a000000-0000-4000-8000-000000000005'::uuid), ('0d000000-0000-4000-8000-000000000101'::uuid, '0a000000-0000-4000-8000-000000000003'::uuid)) v(item, who)
 where not exists (select 1 from public.item_responses r where r.item_id = v.item and r.responder_member_id = v.who);
insert into public.items (id, member_id, kind, title, description, brand_label, state, group_id) values
  ('0d000000-0000-4000-8000-000000000102', '0a000000-0000-4000-8000-000000000011', 'product', 'Country sourdough loaf', 'Naturally leavened.', 'QA Corner Bakery', 'published', '0b000000-0000-4000-8000-000000000001'),
  ('0d000000-0000-4000-8000-000000000103', '0a000000-0000-4000-8000-000000000011', 'service', 'Bread-baking lesson', 'One hour, at the shop.', 'QA Corner Bakery', 'published', '0b000000-0000-4000-8000-000000000001')
on conflict (id) do nothing;
insert into public.item_products (item_id, price_cents, price_unit) values ('0d000000-0000-4000-8000-000000000102', 900, 'loaf') on conflict (item_id) do nothing;
insert into public.item_services (item_id, rate_model, rate_cents) values ('0d000000-0000-4000-8000-000000000103', 'hourly', 4000) on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select v.item, '0c000000-0000-4000-8000-000000000001', v.kind, 'approved' from (values ('0d000000-0000-4000-8000-000000000102'::uuid, 'ongoing'), ('0d000000-0000-4000-8000-000000000103'::uuid, 'by_appointment')) v(item, kind)
 where not exists (select 1 from public.item_locations l where l.item_id = v.item);
insert into public.item_responses (item_id, responder_member_id, response_kind)
select '0d000000-0000-4000-8000-000000000102', '0a000000-0000-4000-8000-000000000005', 'purchase'
 where not exists (select 1 from public.item_responses where item_id = '0d000000-0000-4000-8000-000000000102' and responder_member_id = '0a000000-0000-4000-8000-000000000005');
insert into public.locations (id, member_id, kind, label, slug, geography, place_id, discoverability)
values ('0c000000-0000-4000-8000-000000000002', '0a000000-0000-4000-8000-000000000012', 'permanent', 'QA Oak Park Commons, main spot', 'qa-oak-park-commons-green',
  ST_GeogFromText('POINT(-121.4720 38.5420)'), (select id from public.places where slug = 'oak-park' limit 1), 'listed')
on conflict (id) do nothing;
insert into public.groups (id, kind, purpose, name, slug, public_id, description, lifecycle_state, discoverability, founder_member_id, anchor_location_id)
values ('0b000000-0000-4000-8000-000000000002', 'group', 'gather', 'QA Oak Park Commons', 'qa-oak-park-commons', 'qa0p01',
  'A seeded place Page for the browser suite.', 'active', 'listed', '0a000000-0000-4000-8000-000000000012', '0c000000-0000-4000-8000-000000000002')
on conflict (id) do nothing;
update public.groups set discoverability = 'listed' where id = '0b000000-0000-4000-8000-000000000002';
insert into public.group_memberships (group_id, member_id, role, source, relationship, confirmed_by_member_id, confirmed_at) values
  ('0b000000-0000-4000-8000-000000000002', '0a000000-0000-4000-8000-000000000012', 'steward', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000002', '0a000000-0000-4000-8000-000000000003', 'member', 'explicit', 'member', '0a000000-0000-4000-8000-000000000012', now()),
  ('0b000000-0000-4000-8000-000000000002', '0a000000-0000-4000-8000-000000000004', 'member', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000002', '0a000000-0000-4000-8000-000000000002', 'member', 'soft_via_follow', 'follower', null, null)
on conflict (group_id, member_id) do nothing;
insert into public.page_posts (id, group_id, body, starts_at, location_id, lifecycle_state, discoverability) values
  ('0e000000-0000-4000-8000-000000000201', '0b000000-0000-4000-8000-000000000002', 'Saturday at QA Oak Park Commons: come along.', date_trunc('day', now()) + interval '3 days 17 hours', '0c000000-0000-4000-8000-000000000002', 'active', 'listed'),
  ('0e000000-0000-4000-8000-000000000202', '0b000000-0000-4000-8000-000000000002', 'Thanks to everyone who came last week.', null, null, 'active', 'listed')
on conflict (id) do nothing;
insert into public.items (id, member_id, kind, title, description, state, group_id)
values ('0d000000-0000-4000-8000-000000000201', '0a000000-0000-4000-8000-000000000012', 'gathering', 'QA Oak Park Commons meetup', 'Come along.', 'published', '0b000000-0000-4000-8000-000000000002')
on conflict (id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values ('0d000000-0000-4000-8000-000000000201', date_trunc('day', now()) + interval '5 days 18 hours')
on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select '0d000000-0000-4000-8000-000000000201', '0c000000-0000-4000-8000-000000000002', 'one_time', 'approved'
 where not exists (select 1 from public.item_locations where item_id = '0d000000-0000-4000-8000-000000000201');
insert into public.item_responses (item_id, responder_member_id, response_kind)
select v.item, v.who, 'rsvp' from (values ('0d000000-0000-4000-8000-000000000201'::uuid, '0a000000-0000-4000-8000-000000000005'::uuid), ('0d000000-0000-4000-8000-000000000201'::uuid, '0a000000-0000-4000-8000-000000000003'::uuid)) v(item, who)
 where not exists (select 1 from public.item_responses r where r.item_id = v.item and r.responder_member_id = v.who);
insert into public.locations (id, member_id, kind, label, slug, geography, place_id, discoverability)
values ('0c000000-0000-4000-8000-000000000003', '0a000000-0000-4000-8000-000000000013', 'permanent', 'QA River Run Club, main spot', 'qa-river-run-club-start',
  ST_GeogFromText('POINT(-121.4740 38.5430)'), (select id from public.places where slug = 'oak-park' limit 1), 'listed')
on conflict (id) do nothing;
insert into public.groups (id, kind, purpose, name, slug, public_id, description, lifecycle_state, discoverability, founder_member_id, anchor_location_id)
values ('0b000000-0000-4000-8000-000000000003', 'group', 'gather', 'QA River Run Club', 'qa-river-run-club', 'qa0n01',
  'A seeded interest Page for the browser suite.', 'active', 'listed', '0a000000-0000-4000-8000-000000000013', '0c000000-0000-4000-8000-000000000003')
on conflict (id) do nothing;
update public.groups set discoverability = 'listed' where id = '0b000000-0000-4000-8000-000000000003';
insert into public.group_memberships (group_id, member_id, role, source, relationship, confirmed_by_member_id, confirmed_at) values
  ('0b000000-0000-4000-8000-000000000003', '0a000000-0000-4000-8000-000000000013', 'steward', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000003', '0a000000-0000-4000-8000-000000000003', 'member', 'explicit', 'member', '0a000000-0000-4000-8000-000000000013', now()),
  ('0b000000-0000-4000-8000-000000000003', '0a000000-0000-4000-8000-000000000004', 'member', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000003', '0a000000-0000-4000-8000-000000000002', 'member', 'soft_via_follow', 'follower', null, null)
on conflict (group_id, member_id) do nothing;
insert into public.page_posts (id, group_id, body, starts_at, location_id, lifecycle_state, discoverability) values
  ('0e000000-0000-4000-8000-000000000301', '0b000000-0000-4000-8000-000000000003', 'Saturday at QA River Run Club: come along.', date_trunc('day', now()) + interval '3 days 17 hours', '0c000000-0000-4000-8000-000000000003', 'active', 'listed'),
  ('0e000000-0000-4000-8000-000000000302', '0b000000-0000-4000-8000-000000000003', 'Thanks to everyone who came last week.', null, null, 'active', 'listed')
on conflict (id) do nothing;
insert into public.items (id, member_id, kind, title, description, state, group_id)
values ('0d000000-0000-4000-8000-000000000301', '0a000000-0000-4000-8000-000000000013', 'gathering', 'QA River Run Club meetup', 'Come along.', 'published', '0b000000-0000-4000-8000-000000000003')
on conflict (id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values ('0d000000-0000-4000-8000-000000000301', date_trunc('day', now()) + interval '5 days 18 hours')
on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select '0d000000-0000-4000-8000-000000000301', '0c000000-0000-4000-8000-000000000003', 'one_time', 'approved'
 where not exists (select 1 from public.item_locations where item_id = '0d000000-0000-4000-8000-000000000301');
insert into public.item_responses (item_id, responder_member_id, response_kind)
select v.item, v.who, 'rsvp' from (values ('0d000000-0000-4000-8000-000000000301'::uuid, '0a000000-0000-4000-8000-000000000005'::uuid), ('0d000000-0000-4000-8000-000000000301'::uuid, '0a000000-0000-4000-8000-000000000003'::uuid)) v(item, who)
 where not exists (select 1 from public.item_responses r where r.item_id = v.item and r.responder_member_id = v.who);
insert into public.locations (id, member_id, kind, label, slug, geography, place_id, discoverability)
values ('0c000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-000000000014', 'permanent', 'QA Pottery Studio, main spot', 'qa-pottery-studio-room',
  ST_GeogFromText('POINT(-121.4760 38.5440)'), (select id from public.places where slug = 'oak-park' limit 1), 'listed')
on conflict (id) do nothing;
insert into public.groups (id, kind, purpose, name, slug, public_id, description, lifecycle_state, discoverability, founder_member_id, anchor_location_id)
values ('0b000000-0000-4000-8000-000000000004', 'group', 'offer', 'QA Pottery Studio', 'qa-pottery-studio', 'qa0r01',
  'A seeded practice Page for the browser suite.', 'active', 'listed', '0a000000-0000-4000-8000-000000000014', '0c000000-0000-4000-8000-000000000004')
on conflict (id) do nothing;
update public.groups set discoverability = 'listed' where id = '0b000000-0000-4000-8000-000000000004';
insert into public.group_memberships (group_id, member_id, role, source, relationship, confirmed_by_member_id, confirmed_at) values
  ('0b000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-000000000014', 'steward', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-000000000003', 'member', 'explicit', 'member', '0a000000-0000-4000-8000-000000000014', now()),
  ('0b000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-000000000004', 'member', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000004', '0a000000-0000-4000-8000-000000000002', 'member', 'soft_via_follow', 'follower', null, null)
on conflict (group_id, member_id) do nothing;
insert into public.page_posts (id, group_id, body, starts_at, location_id, lifecycle_state, discoverability) values
  ('0e000000-0000-4000-8000-000000000401', '0b000000-0000-4000-8000-000000000004', 'Saturday at QA Pottery Studio: come along.', date_trunc('day', now()) + interval '3 days 17 hours', '0c000000-0000-4000-8000-000000000004', 'active', 'listed'),
  ('0e000000-0000-4000-8000-000000000402', '0b000000-0000-4000-8000-000000000004', 'Thanks to everyone who came last week.', null, null, 'active', 'listed')
on conflict (id) do nothing;
insert into public.items (id, member_id, kind, title, description, state, group_id)
values ('0d000000-0000-4000-8000-000000000401', '0a000000-0000-4000-8000-000000000014', 'gathering', 'QA Pottery Studio meetup', 'Come along.', 'published', '0b000000-0000-4000-8000-000000000004')
on conflict (id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values ('0d000000-0000-4000-8000-000000000401', date_trunc('day', now()) + interval '5 days 18 hours')
on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select '0d000000-0000-4000-8000-000000000401', '0c000000-0000-4000-8000-000000000004', 'one_time', 'approved'
 where not exists (select 1 from public.item_locations where item_id = '0d000000-0000-4000-8000-000000000401');
insert into public.item_responses (item_id, responder_member_id, response_kind)
select v.item, v.who, 'rsvp' from (values ('0d000000-0000-4000-8000-000000000401'::uuid, '0a000000-0000-4000-8000-000000000005'::uuid), ('0d000000-0000-4000-8000-000000000401'::uuid, '0a000000-0000-4000-8000-000000000003'::uuid)) v(item, who)
 where not exists (select 1 from public.item_responses r where r.item_id = v.item and r.responder_member_id = v.who);
insert into public.locations (id, member_id, kind, label, slug, geography, place_id, discoverability)
values ('0c000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-000000000015', 'permanent', 'QA Street Fair, main spot', 'qa-street-fair-block',
  ST_GeogFromText('POINT(-121.4780 38.5450)'), (select id from public.places where slug = 'oak-park' limit 1), 'listed')
on conflict (id) do nothing;
insert into public.groups (id, kind, purpose, name, slug, public_id, description, lifecycle_state, discoverability, founder_member_id, anchor_location_id)
values ('0b000000-0000-4000-8000-000000000005', 'group', 'create', 'QA Street Fair', 'qa-street-fair', 'qa0e01',
  'A seeded event Page for the browser suite.', 'active', 'listed', '0a000000-0000-4000-8000-000000000015', '0c000000-0000-4000-8000-000000000005')
on conflict (id) do nothing;
update public.groups set discoverability = 'listed' where id = '0b000000-0000-4000-8000-000000000005';
insert into public.group_memberships (group_id, member_id, role, source, relationship, confirmed_by_member_id, confirmed_at) values
  ('0b000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-000000000015', 'steward', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-000000000003', 'member', 'explicit', 'member', '0a000000-0000-4000-8000-000000000015', now()),
  ('0b000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-000000000004', 'member', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000005', '0a000000-0000-4000-8000-000000000002', 'member', 'soft_via_follow', 'follower', null, null)
on conflict (group_id, member_id) do nothing;
insert into public.page_posts (id, group_id, body, starts_at, location_id, lifecycle_state, discoverability) values
  ('0e000000-0000-4000-8000-000000000501', '0b000000-0000-4000-8000-000000000005', 'Saturday at QA Street Fair: come along.', date_trunc('day', now()) + interval '3 days 17 hours', '0c000000-0000-4000-8000-000000000005', 'active', 'listed'),
  ('0e000000-0000-4000-8000-000000000502', '0b000000-0000-4000-8000-000000000005', 'Thanks to everyone who came last week.', null, null, 'active', 'listed')
on conflict (id) do nothing;
insert into public.items (id, member_id, kind, title, description, state, group_id)
values ('0d000000-0000-4000-8000-000000000501', '0a000000-0000-4000-8000-000000000015', 'gathering', 'QA Street Fair meetup', 'Come along.', 'published', '0b000000-0000-4000-8000-000000000005')
on conflict (id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values ('0d000000-0000-4000-8000-000000000501', date_trunc('day', now()) + interval '5 days 18 hours')
on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select '0d000000-0000-4000-8000-000000000501', '0c000000-0000-4000-8000-000000000005', 'one_time', 'approved'
 where not exists (select 1 from public.item_locations where item_id = '0d000000-0000-4000-8000-000000000501');
insert into public.item_responses (item_id, responder_member_id, response_kind)
select v.item, v.who, 'rsvp' from (values ('0d000000-0000-4000-8000-000000000501'::uuid, '0a000000-0000-4000-8000-000000000005'::uuid), ('0d000000-0000-4000-8000-000000000501'::uuid, '0a000000-0000-4000-8000-000000000003'::uuid)) v(item, who)
 where not exists (select 1 from public.item_responses r where r.item_id = v.item and r.responder_member_id = v.who);
insert into public.locations (id, member_id, kind, label, slug, geography, place_id, discoverability)
values ('0c000000-0000-4000-8000-000000000006', '0a000000-0000-4000-8000-000000000016', 'permanent', 'QA Family, main spot', 'qa-family-home',
  ST_GeogFromText('POINT(-121.4800 38.5460)'), (select id from public.places where slug = 'oak-park' limit 1), 'listed')
on conflict (id) do nothing;
insert into public.groups (id, kind, purpose, name, slug, public_id, description, lifecycle_state, discoverability, founder_member_id, anchor_location_id)
values ('0b000000-0000-4000-8000-000000000006', 'group', 'gather', 'QA Family', 'qa-family', 'qa0f01',
  'A seeded family Page for the browser suite.', 'active', 'private', '0a000000-0000-4000-8000-000000000016', '0c000000-0000-4000-8000-000000000006')
on conflict (id) do nothing;
update public.groups set discoverability = 'private' where id = '0b000000-0000-4000-8000-000000000006';
insert into public.group_memberships (group_id, member_id, role, source, relationship, confirmed_by_member_id, confirmed_at) values
  ('0b000000-0000-4000-8000-000000000006', '0a000000-0000-4000-8000-000000000016', 'steward', 'explicit', 'member', null, null),
  ('0b000000-0000-4000-8000-000000000006', '0a000000-0000-4000-8000-000000000003', 'member', 'explicit', 'member', '0a000000-0000-4000-8000-000000000016', now()),
  ('0b000000-0000-4000-8000-000000000006', '0a000000-0000-4000-8000-000000000004', 'member', 'explicit', 'member', null, null)
on conflict (group_id, member_id) do nothing;
insert into public.page_posts (id, group_id, body, starts_at, location_id, lifecycle_state, discoverability) values
  ('0e000000-0000-4000-8000-000000000601', '0b000000-0000-4000-8000-000000000006', 'Saturday at QA Family: come along.', date_trunc('day', now()) + interval '3 days 17 hours', '0c000000-0000-4000-8000-000000000006', 'active', 'private'),
  ('0e000000-0000-4000-8000-000000000602', '0b000000-0000-4000-8000-000000000006', 'Thanks to everyone who came last week.', null, null, 'active', 'private')
on conflict (id) do nothing;
insert into public.items (id, member_id, kind, title, description, state, group_id)
values ('0d000000-0000-4000-8000-000000000601', '0a000000-0000-4000-8000-000000000016', 'gathering', 'QA Family meetup', 'Come along.', 'published', '0b000000-0000-4000-8000-000000000006')
on conflict (id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values ('0d000000-0000-4000-8000-000000000601', date_trunc('day', now()) + interval '5 days 18 hours')
on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select '0d000000-0000-4000-8000-000000000601', '0c000000-0000-4000-8000-000000000006', 'one_time', 'approved'
 where not exists (select 1 from public.item_locations where item_id = '0d000000-0000-4000-8000-000000000601');
insert into public.item_responses (item_id, responder_member_id, response_kind)
select v.item, v.who, 'rsvp' from (values ('0d000000-0000-4000-8000-000000000601'::uuid, '0a000000-0000-4000-8000-000000000005'::uuid), ('0d000000-0000-4000-8000-000000000601'::uuid, '0a000000-0000-4000-8000-000000000003'::uuid)) v(item, who)
 where not exists (select 1 from public.item_responses r where r.item_id = v.item and r.responder_member_id = v.who);

-- 3. Things a member posted without a Page: /m/<handle>/{p,s,e}/...
insert into public.items (id, member_id, kind, title, description, state, group_id) values
  ('0d000000-0000-4000-8000-000000009901', '0a000000-0000-4000-8000-000000000003', 'product', 'Jar of plum jam', 'From the backyard tree.', 'published', null),
  ('0d000000-0000-4000-8000-000000009902', '0a000000-0000-4000-8000-000000000003', 'service', 'Bike tune-up', 'Bring it round.', 'published', null),
  ('0d000000-0000-4000-8000-000000009903', '0a000000-0000-4000-8000-000000000003', 'gathering', 'Porch music night', 'Bring an instrument.', 'published', null)
on conflict (id) do nothing;
insert into public.item_products (item_id, price_cents, price_unit) values ('0d000000-0000-4000-8000-000000009901', 600, 'jar') on conflict (item_id) do nothing;
insert into public.item_services (item_id, rate_model, rate_cents) values ('0d000000-0000-4000-8000-000000009902', 'flat', 2500) on conflict (item_id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values ('0d000000-0000-4000-8000-000000009903', date_trunc('day', now()) + interval '4 days 19 hours')
on conflict (item_id) do nothing;

-- 4. Tags on every Page, and one report for the operator's queue.
insert into public.tags (id, label, normalized, status, created_by) values
  ('0f000000-0000-4000-8000-000000000001', 'Local food', 'qa-local-food', 'visible', '0a000000-0000-4000-8000-000000000011'),
  ('0f000000-0000-4000-8000-000000000002', 'Weekend', 'qa-weekend', 'visible', '0a000000-0000-4000-8000-000000000011')
on conflict do nothing;
insert into public.page_tags (group_id, tag_id)
select g.id, t.id from public.groups g, public.tags t
 where g.id::text like '0b000000-0000-4000-8000-%' and t.id::text like '0f000000-0000-4000-8000-00000000000%'
on conflict do nothing;
insert into public.reports (id, reporter_member_id, subject_kind, subject_id, body) values
  ('0f000000-0000-4000-8000-000000000101', '0a000000-0000-4000-8000-000000000001', 'group', '0b000000-0000-4000-8000-000000000001', 'Seeded report for the operator queue.')
on conflict (id) do nothing;

commit;

refresh materialized view public.discoverable_items;
