// T163 (#77) — the metro catalog and the waitlist, against a real database.
//
// The unit tests mock the pool, so they prove the handler's logic and nothing
// about whether the unique constraint exists or whether 296 metros are
// actually there. Criterion 1 is a coverage claim about reference data and
// criterion 4 is a claim about a database constraint; neither can be checked
// against a mock.

import { describe, it, expect } from 'vitest'
import { Pool } from 'pg'
import { readFileSync, readdirSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { requireRunnable } from './support/runnable'
import { databaseWriteSafety } from './support/write-safe'

const DATABASE_URL =
  process.env.DATABASE_URL ??
  process.env.POSTGRES_URL_NON_POOLING ??
  process.env.POSTGRES_URL

const MIG = resolve(__dirname, '..', 'supabase', 'migrations')
const FILE = readdirSync(MIG).find((f) => /^\d{14}_metro_waitlist\.sql$/.test(f))

describe('T163 — the migration file', () => {
  it('exists, timestamped per #39', () => {
    expect(FILE, 'expected a YYYYMMDDHHMMSS_metro_waitlist.sql').toBeTruthy()
  })

  const raw = FILE && existsSync(resolve(MIG, FILE)) ? readFileSync(resolve(MIG, FILE), 'utf8') : ''

  it('never opens a metro — the seed and the schema leave is_open false', () => {
    // Criterion 12. The one `is_open = true` is the metro that is already
    // open; nothing else in the file sets it, and nothing computes it.
    const opens = raw.match(/is_open\s*=\s*true/gi) ?? []
    expect(opens).toHaveLength(1)
    expect(raw).toMatch(/set is_open = true where slug = 'sacramento-roseville-ca'/i)
  })

  it('cites the Census delineation file it was generated from', () => {
    // The coverage claim in criterion 1 is only as good as its source, so the
    // source is named in the file rather than trusted to memory.
    expect(raw).toMatch(/census/i)
    expect(raw).toMatch(/list1_2023\.xlsx/i)
  })

  it('never sells, ranks or prices a place in line', () => {
    // Scanned over the SCHEMA half only, which is where a `price` or `rank`
    // column would live. The seed below it is 296 US place names, and a name
    // legitimately contains these substrings — "Bowling Green-Glasgow-
    // Franklin, KY" carries "rank". Scanning data for schema words finds
    // Kentucky, which is the wrong answer to the right question.
    const schema = raw.split('-- GENERATED by')[0]
    const ddl = schema
      .split('\n')
      .map((l) => l.replace(/--.*$/, ''))
      .join('\n')
      .replace(/'(?:[^']|'')*'/g, "''")
    for (const w of ['price', 'payment', 'paid', 'rank', 'referral', 'invite_code', 'position']) {
      expect(ddl.toLowerCase(), `metro_waitlist must not mention ${w}`).not.toContain(w)
    }
  })
})

const RUNNABLE = requireRunnable({
  claim: 'every US metro is selectable and the waitlist can hold a person only once',
  available: !!DATABASE_URL,
  remedy:
    'run `supabase start`, then put DATABASE_URL in .env.test.local ' +
    '(recipe in .env.local.example)',
})

const query = async <T>(sql: string, params: unknown[] = []): Promise<T[]> => {
  const pool = new Pool({ connectionString: DATABASE_URL })
  try {
    const { rows } = await pool.query(sql, params)
    return rows as T[]
  } finally {
    await pool.end()
  }
}

describe.skipIf(!RUNNABLE)('T163 — the metro catalog (c1)', () => {
  it('holds every US metro — 184 CSAs plus the 112 metros in no CSA', async () => {
    const [{ n }] = await query<{ n: string }>(
      `select count(*)::text as n from public.metro_polygons`,
    )
    expect(Number(n)).toBe(296)
  })

  it('records which code space each row is in', async () => {
    const rows = await query<{ code_kind: string; n: string }>(
      `select code_kind, count(*)::text as n from public.metro_polygons group by code_kind order by code_kind`,
    )
    const by = Object.fromEntries(rows.map((r) => [r.code_kind, Number(r.n)]))
    expect(by.csa).toBe(184)
    expect(by.cbsa).toBe(112)
  })

  it('has the scenario\'s own example in it', async () => {
    // "Someone in Boise signs up."
    const rows = await query<{ name: string }>(
      `select name from public.metro_polygons where slug like 'boise%'`,
    )
    expect(rows.length).toBeGreaterThan(0)
  })

  it('keeps the launch metro, its polygon, and its open state', async () => {
    const rows = await query<{ is_open: boolean; has_geo: boolean; csa_code: string }>(
      `select is_open, geography is not null as has_geo, csa_code
         from public.metro_polygons where slug = 'sacramento-roseville-ca'`,
    )
    expect(rows[0]).toMatchObject({ is_open: true, has_geo: true, csa_code: '472' })
  })

  it('opens exactly one metro — crossing a threshold never opens one (c12)', async () => {
    const [{ n }] = await query<{ n: string }>(
      `select count(*)::text as n from public.metro_polygons where is_open`,
    )
    expect(Number(n)).toBe(1)
  })

  it('leaves every unopened metro without a polygon, and that is fine', async () => {
    // A person PICKS their metro (criterion 2 forbids IP, defaults and
    // nearest-match), so an unopened metro needs no boundary.
    const [{ n }] = await query<{ n: string }>(
      `select count(*)::text as n from public.metro_polygons where geography is not null`,
    )
    expect(Number(n)).toBe(1)
  })

  it('never resolves an unopened metro as anyone\'s home metro', async () => {
    // resolve_home_metro tests ST_Contains against the polygon, which is NULL
    // — never true — for a catalog-only row. Asserted rather than assumed.
    const rows = await query<{ id: string | null }>(
      `select public.resolve_home_metro(st_point(-116.2023, 43.6150)::geography) as id`,
    )
    expect(rows[0].id).toBeNull()
  })

  it('carries per-metro thresholds, defaulted to the approved values (c11)', async () => {
    const rows = await query<{ creator_threshold: number; patron_threshold: number }>(
      `select creator_threshold, patron_threshold from public.metro_polygons where slug like 'boise%'`,
    )
    expect(rows[0]).toMatchObject({ creator_threshold: 50, patron_threshold: 250 })
  })

  it('lets a threshold be changed with an UPDATE — no migration, no deploy (c11)', async () => {
    const pool = new Pool({ connectionString: DATABASE_URL })
    const client = await pool.connect()
    try {
      await client.query('begin')
      await client.query(
        `update public.metro_polygons set creator_threshold = 7 where slug like 'boise%'`,
      )
      const { rows } = await client.query(
        `select creator_threshold from public.metro_polygons where slug like 'boise%'`,
      )
      expect(rows[0].creator_threshold).toBe(7)
    } finally {
      await client.query('rollback')
      client.release()
      await pool.end()
    }
  })
})

describe.skipIf(!RUNNABLE)('T163 — metro_waitlist shape', () => {
  it('has RLS on, with read policies and no write policy (ADR-7)', async () => {
    const [{ rls }] = await query<{ rls: boolean }>(
      `select relrowsecurity as rls from pg_class where oid = 'public.metro_waitlist'::regclass`,
    )
    expect(rls).toBe(true)
    const policies = await query<{ polcmd: string }>(
      `select polcmd from pg_policy where polrelid = 'public.metro_waitlist'::regclass`,
    )
    expect(policies.length).toBeGreaterThan(0)
    expect(policies.every((p) => p.polcmd === 'r')).toBe(true)
  })

  it('constrains role to exactly creator and patron, with no default (c3)', async () => {
    const checks = await query<{ def: string }>(
      `select pg_get_constraintdef(oid) as def from pg_constraint
        where conrelid = 'public.metro_waitlist'::regclass and contype = 'c'`,
    )
    const all = checks.map((c) => c.def).join(' ')
    expect(all).toContain('creator')
    expect(all).toContain('patron')

    const [{ d }] = await query<{ d: string | null }>(
      `select column_default as d from information_schema.columns
        where table_schema='public' and table_name='metro_waitlist' and column_name='role'`,
    )
    // A default role is a pre-selection by another name.
    expect(d).toBeNull()
  })

  it('is unique on the person — idempotency is the constraint, not the handler (c4)', async () => {
    const rows = await query<{ def: string }>(
      `select pg_get_constraintdef(oid) as def from pg_constraint
        where conrelid = 'public.metro_waitlist'::regclass and contype = 'u'`,
    )
    expect(rows.some((r) => /\(member_id\)/.test(r.def))).toBe(true)
  })
})

// ---------------------------------------------------------------------------
// Behaviour, against seeded rows.

const safety = databaseWriteSafety(DATABASE_URL, process.env)
const WRITABLE = requireRunnable({
  claim: 'the waitlist actually rejects a second row for one person, and a metro change moves the count',
  available: safety.safe,
  remedy: `${safety.reason} Recipe in .env.local.example`,
})

describe.skipIf(!WRITABLE)('T163 — the constraint, against real rows', () => {
  const inRollback = async <T>(
    fn: (q: (sql: string, p?: unknown[]) => Promise<Record<string, unknown>[]>) => Promise<T>,
  ): Promise<T> => {
    const pool = new Pool({ connectionString: DATABASE_URL })
    const client = await pool.connect()
    try {
      await client.query('begin')
      const q = async (sql: string, p: unknown[] = []) =>
        (await client.query(sql, p)).rows as Record<string, unknown>[]
      return await fn(q)
    } finally {
      await client.query('rollback')
      client.release()
      await pool.end()
    }
  }

  const ids = async (q: (sql: string, p?: unknown[]) => Promise<Record<string, unknown>[]>) => {
    const [{ id: memberId }] = (await q(`select id from public.members limit 1`)) as { id: string }[]
    const metros = (await q(
      `select id from public.metro_polygons where slug in ('boise-city-mountain-home-ontario-id-or','reno-carson-city-gardnerville-ranchos-nv-ca') order by slug`,
    )) as { id: string }[]
    if (metros.length < 2) {
      throw new Error(`expected two seeded metros for this fixture, got ${metros.length}`)
    }
    return { memberId, a: metros[0].id, b: metros[1].id }
  }

  it('rejects a second row for the same person, at the database (c4)', async () => {
    const err = await inRollback(async (q) => {
      const { memberId, a, b } = await ids(q)
      await q(`insert into public.metro_waitlist (member_id, metro_id, role) values ($1,$2,'creator')`, [memberId, a])
      try {
        await q(`insert into public.metro_waitlist (member_id, metro_id, role) values ($1,$2,'patron')`, [memberId, b])
        return null
      } catch (e) {
        return (e as Error).message
      }
    })
    expect(err, 'a second waitlist row for one person must be rejected').toBeTruthy()
    expect(err).toMatch(/unique|duplicate/i)
  })

  it('rejects a role that is neither creator nor patron', async () => {
    const err = await inRollback(async (q) => {
      const { memberId, a } = await ids(q)
      try {
        await q(`insert into public.metro_waitlist (member_id, metro_id, role) values ($1,$2,'lurker')`, [memberId, a])
        return null
      } catch (e) {
        return (e as Error).message
      }
    })
    expect(err).toBeTruthy()
  })

  it('cascades: removing the member removes their waitlist row', async () => {
    // Its own throwaway member, not the first one in the table: an
    // established member cannot be deleted at all (place_events restricts it),
    // so reusing one tests the wrong constraint and fails for the wrong reason.
    const remaining = await inRollback(async (q) => {
      const { a } = await ids(q)
      const [{ id: memberId }] = (await q(
        `insert into public.members (handle, display_name)
         values ('t163-cascade', 'T163 Cascade') returning id`,
      )) as { id: string }[]
      await q(`insert into public.metro_waitlist (member_id, metro_id, role) values ($1,$2,'patron')`, [memberId, a])
      await q(`delete from public.members where id = $1`, [memberId])
      return await q(`select id from public.metro_waitlist where member_id = $1`, [memberId])
    })
    expect(remaining).toEqual([])
  })

  it('counters recompute to the same numbers as the rows they summarise (c6)', async () => {
    // The counters are maintained by the handler rather than derived at read
    // time, so the thing worth testing is that the two agree.
    const rows = await inRollback(async (q) => {
      const { memberId, a } = await ids(q)
      await q(`insert into public.metro_waitlist (member_id, metro_id, role) values ($1,$2,'creator')`, [memberId, a])
      await q(`update public.metro_polygons set creator_count = creator_count + 1 where id = $1`, [a])
      return await q(
        `select m.creator_count,
                (select count(*) from public.metro_waitlist w
                  where w.metro_id = m.id and w.role = 'creator') as actual
           from public.metro_polygons m where m.id = $1`,
        [a],
      )
    })
    expect(Number(rows[0].creator_count)).toBe(Number(rows[0].actual))
  })
})
