#!/usr/bin/env tsx
// T163 (#77) — regenerate the metro catalog seed from the Census delineation file.
//
// F076 criterion 1: every US metro is present and selectable at signup, and a
// person cannot reach a state where their metro is absent. That is a coverage
// claim about reference data, so the data comes from the authority rather than
// from anyone's memory, and this script is how it is replayed.
//
//   Source: U.S. Census Bureau, Core Based Statistical Areas delineation file,
//           July 2023 — list1_2023.xlsx
//           https://www2.census.gov/programs-surveys/metro-micro/geographies/
//             reference-files/2023/delineation-files/list1_2023.xlsx
//
// GRAIN: CSA where one exists, else the Metropolitan Statistical Area.
// Migration 031 § D2 already chose CSA grain for this table; a Metropolitan
// area that belongs to no CSA would simply be missing at that grain, so those
// are carried at CBSA grain and `code_kind` records which is which.
//
// Micropolitan areas are deliberately excluded — they are by definition not
// metros (an urban core of 10,000-50,000). That leaves rural America choosing
// a nearby metro rather than its own town, which is the same known hole
// feed-metro.ts already names. Recorded, not silently dropped.
//
// Usage:  npx tsx scripts/build-metro-catalog.ts <list1_2023.xlsx> > out.sql

import { execFileSync } from 'node:child_process'

interface Metro {
  code: string
  codeKind: 'csa' | 'cbsa'
  name: string
}

/** Slug matching the one migration 031 seeded by hand, so Sacramento collides. */
export function metroSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

/** Parse the sheet with python3's stdlib — no xlsx dependency enters the app. */
function readRows(xlsxPath: string): Record<string, string>[] {
  const py = `
import zipfile, xml.etree.ElementTree as ET, json, sys
NS={'m':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
z=zipfile.ZipFile(sys.argv[1])
root=ET.fromstring(z.read('xl/sharedStrings.xml'))
ss=[''.join(t.text or '' for t in si.iter('{http://schemas.openxmlformats.org/spreadsheetml/2006/main}t')) for si in root.findall('m:si',NS)]
sh=ET.fromstring(z.read('xl/worksheets/sheet1.xml'))
out=[]
for r in sh.findall('.//m:row',NS):
    cells={}
    for c in r.findall('m:c',NS):
        col=''.join(ch for ch in c.get('r') if ch.isalpha())
        v=c.find('m:v',NS)
        if v is None: continue
        cells[col]= ss[int(v.text)] if c.get('t')=='s' else v.text
    out.append(cells)
json.dump(out, sys.stdout)
`
  return JSON.parse(execFileSync('python3', ['-c', py, xlsxPath], { maxBuffer: 64 * 1024 * 1024 }).toString())
}

export function buildCatalog(rows: Record<string, string>[]): Metro[] {
  const data = rows.filter((r) => /^\d{5}$/.test(r.A ?? ''))
  const csas = new Map<string, string>()
  const metroCsa = new Map<string, string | undefined>()
  const metroTitle = new Map<string, string>()

  for (const r of data) {
    if (r.C && r.G) csas.set(r.C, r.G)
    if (r.E === 'Metropolitan Statistical Area') {
      metroTitle.set(r.A, r.D ?? '')
      if (!metroCsa.has(r.A)) metroCsa.set(r.A, r.C)
      // A metro spans counties; the CSA code is on every row it belongs to.
      if (r.C) metroCsa.set(r.A, r.C)
    }
  }

  const out: Metro[] = []
  for (const [code, name] of csas) out.push({ code, codeKind: 'csa', name })
  for (const [code, csa] of metroCsa) {
    if (csa) continue
    out.push({ code, codeKind: 'cbsa', name: metroTitle.get(code)! })
  }
  return out.sort((a, b) => a.name.localeCompare(b.name))
}

function main() {
  const path = process.argv[2]
  if (!path) throw new Error('usage: build-metro-catalog.ts <list1_2023.xlsx>')
  const catalog = buildCatalog(readRows(path))

  const seen = new Set<string>()
  for (const m of catalog) {
    const s = metroSlug(m.name)
    if (seen.has(s)) throw new Error(`duplicate slug ${s} — the catalog must be unique by slug`)
    seen.add(s)
  }

  const lit = (s: string) => `'${s.replace(/'/g, "''")}'`
  const values = catalog
    .map((m) => `  (${lit(m.name)}, ${lit(metroSlug(m.name))}, ${lit(m.code)}, ${lit(m.codeKind)})`)
    .join(',\n')

  process.stdout.write(
    `-- GENERATED by scripts/build-metro-catalog.ts from the U.S. Census\n` +
      `-- Core Based Statistical Areas delineation file, July 2023 (list1_2023.xlsx).\n` +
      `-- ${catalog.length} metros: CSA grain where a CSA exists, else the\n` +
      `-- Metropolitan Statistical Area. Do not hand-edit; re-run the script.\n\n` +
      `insert into public.metro_polygons (name, slug, csa_code, code_kind)\nvalues\n${values}\non conflict (slug) do nothing;\n`,
  )
}

if (require.main === module) main()
