#!/usr/bin/env tsx
// Writes src/lib/migrations/manifest.ts from supabase/migrations/.
//
// WHY A GENERATED FILE AND NOT A DIRECTORY READ. The schema health endpoint
// has to know which migrations THIS BUILD carries, and it runs on Vercel where
// `supabase/migrations/` is not in the bundle — a runtime readdir there finds
// nothing, and "nothing" compares equal to every database. The list has to be
// compiled in. Same pattern, and the same reason, as src/ontology/registry.json.
//
// Committed, and a test compares it against the directory, so a migration added
// without regenerating goes red here rather than shipping a build that thinks
// the schema is fine.

import { readdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const MIG = resolve(ROOT, 'supabase', 'migrations')
const OUT = resolve(ROOT, 'src', 'lib', 'migrations', 'manifest.ts')

/** The version is the filename's leading number — `039` or `20260921200710`.
 *  Exactly what `supabase_migrations.schema_migrations.version` holds. */
export function versionsIn(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.sql'))
    .map((f) => f.split('_')[0])
    .filter((v) => /^\d+$/.test(v))
    .sort()
}

export function render(versions: string[]): string {
  return `// GENERATED by scripts/generate-migration-manifest.ts — do not edit.
//
// Every migration version this build carries. Read by /api/health/schema,
// which compares it against the database the deployment is actually pointed
// at. Regenerate with \`npm run migrations:manifest\` and commit both.

export const MIGRATION_VERSIONS: readonly string[] = [
${versions.map((v) => `  '${v}',`).join('\n')}
]
`
}

function main() {
  const versions = versionsIn(MIG)
  // An empty list is the failure this whole guard exists to avoid: it would
  // make every database look up to date. Refuse to write one.
  if (versions.length === 0) {
    console.error('generate-migration-manifest: found no migrations — refusing to write an empty manifest.')
    process.exit(1)
  }
  const next = render(versions)
  const check = process.argv.includes('--check')
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
  if (check) {
    if (current !== next) {
      console.error('generate-migration-manifest: manifest.ts is stale. Run `npm run migrations:manifest` and commit it.')
      process.exit(1)
    }
    console.log(`generate-migration-manifest: up to date (${versions.length} migrations).`)
    return
  }
  writeFileSync(OUT, next)
  console.log(`generate-migration-manifest: wrote ${versions.length} versions.`)
}

if (process.argv[1] && process.argv[1].endsWith('generate-migration-manifest.ts')) main()
