#!/usr/bin/env tsx
// #269 — the persona seed: one person per role, a Page of every kind with
// every component in use. Source of truth is evals/personas.ts.
//
//   tsx scripts/seed-personas.ts --generate   writes supabase/seeds/personas.sql
//   tsx scripts/seed-personas.ts --check      fails if that file is stale
//   tsx scripts/seed-personas.ts --apply      applies it to DATABASE_URL
//
// --apply REFUSES any host that is not local (localhost, 127.0.0.1, ::1). The
// password in evals/personas.ts is a local test value and must never reach a
// real database. The check is a hard exit, not a warning.

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { Client } from 'pg'
import { PERSONAS, PAGES, PERSONA_PASSWORD, persona, type SeededPage } from '../evals/personas'

const ROOT = resolve(__dirname, '..')
const OUT = resolve(ROOT, 'supabase/seeds/personas.sql')
const LOCAL = new Set(['localhost', '127.0.0.1', '::1', '[::1]'])

const pad = (n: number) => String(n).padStart(2, '0')
const gid = (i: number) => `0b000000-0000-4000-8000-0000000000${pad(i + 1)}`
const lid = (i: number) => `0c000000-0000-4000-8000-0000000000${pad(i + 1)}`
const iid = (i: number, j: number) => `0d000000-0000-4000-8000-00000000${pad(i + 1)}${pad(j)}`
const postId = (i: number, j: number) => `0e000000-0000-4000-8000-00000000${pad(i + 1)}${pad(j)}`
const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const label = (key: string) => 'QA ' + key[0]!.toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1')
const OAK_PARK = `(select id from public.places where slug = 'oak-park' limit 1)`

export function generate(): string {
  const people = PERSONAS.filter((p) => p.id)
  const ownerOf = (page: SeededPage) => people.find((p) => p.owns === page.key)!
  const member = persona('member').id!
  const applicant = persona('applicant').id!
  const follower = persona('follower').id!
  const rsvp = persona('rsvp').id!
  const out: string[] = []
  const w = (s: string) => out.push(s)

  w(`-- GENERATED by scripts/seed-personas.ts from evals/personas.ts. Do not edit.
--
-- #269 — one persona per role, for the browser suite and the screenshot
-- matrix. LOCAL ONLY: scripts/seed-personas.ts --apply refuses any host that
-- is not local, and the password is a local test value.
--
-- PRIVILEGED, like every seed here (supabase/seeds/README.md): it writes as
-- postgres, through no handler. It shows what each role SEES; it proves
-- nothing about what a handler WRITES.
--
-- Join approval is not built, so \`member\` and \`applicant\` differ only in
-- group_memberships.confirmed_at. Products and services sit on the business
-- Page only: an item's own page resolves under a business Page or under its
-- poster, never under another kind of Page.

begin;
set local eval.skip_signup_hook = 'on';

-- 1. People.
`)
  for (const p of people) {
    w(`insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at, confirmation_token, recovery_token,
  email_change_token_new, email_change, email_change_token_current, reauthentication_token, phone_change, phone_change_token)
values (${q(p.id!)}, '00000000-0000-0000-0000-000000000000', 'authenticated', 'authenticated', ${q(p.email!)},
  extensions.crypt(${q(PERSONA_PASSWORD)}, extensions.gen_salt('bf')), now(),
  '{"provider":"email","providers":["email"]}', '{}', now(), now(), '', '', '', '', '', '', '', '')
on conflict (id) do nothing;
insert into auth.identities (id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
values (${q(p.id!)}, ${q(p.id!)}, ${q(p.id!)}, ${q(JSON.stringify({ sub: p.id, email: p.email, email_verified: true }))},
  'email', now(), now(), now())
on conflict do nothing;
insert into public.members (id, handle, display_name, stakeholder_visibility, home_metro_id)
values (${q(p.id!)}, ${q(p.handle!)}, ${q(label(p.key))}, 'public',
  (select id from public.metro_polygons where slug = 'sacramento-roseville-ca'))
on conflict (id) do nothing;
insert into public.member_place_interests (member_id, place_id, scope_kind)
select ${q(p.id!)}, ${OAK_PARK}, 'primary_home'
 where not exists (select 1 from public.member_place_interests where member_id = ${q(p.id!)} and scope_kind = 'primary_home');
`)
  }

  w(`\n-- 2. A Page of every kind, its place, and the people around it.\n`)
  PAGES.forEach((pg, i) => {
    const o = ownerOf(pg).id!
    const vis = pg.private ? 'private' : 'listed'
    const role = pg.kind === 'business' ? 'owner' : 'steward'
    const lon = (-121.47 - 0.002 * i).toFixed(4)
    const lat = (38.541 + 0.001 * i).toFixed(4)
    w(`insert into public.locations (id, member_id, kind, label, slug, geography, place_id, discoverability)
values (${q(lid(i))}, ${q(o)}, 'permanent', ${q(`${pg.name}, main spot`)}, ${q(pg.locationSlug)},
  ST_GeogFromText('POINT(${lon} ${lat})'), ${OAK_PARK}, 'listed')
on conflict (id) do nothing;
insert into public.groups (id, kind, use_case, name, slug, public_id, description, lifecycle_state, discoverability, founder_member_id, anchor_location_id)
values (${q(gid(i))}, ${q(pg.kind)}, ${q(pg.useCase)}, ${q(pg.name)}, ${q(pg.slug)}, ${q(pg.publicId)},
  ${q(`A seeded ${pg.key} Page for the browser suite.`)}, 'active', ${q(vis)}, ${q(o)}, ${q(lid(i))})
on conflict (id) do nothing;
update public.groups set discoverability = ${q(vis)} where id = ${q(gid(i))};
`)
    if (pg.kind === 'business') {
      w(`insert into public.group_businesses (group_id, display_name, public_description)
values (${q(gid(i))}, ${q(pg.name)}, 'Bread and pastries, baked in Oak Park.') on conflict do nothing;
`)
    }
    const rows = [
      `(${q(gid(i))}, ${q(o)}, ${q(role)}, 'explicit', 'member', null, null)`,
      `(${q(gid(i))}, ${q(member)}, 'member', 'explicit', 'member', ${q(o)}, now())`,
      `(${q(gid(i))}, ${q(applicant)}, 'member', 'explicit', 'member', null, null)`,
      ...(pg.private ? [] : [`(${q(gid(i))}, ${q(follower)}, 'member', 'soft_via_follow', 'follower', null, null)`]),
    ]
    w(`insert into public.group_memberships (group_id, member_id, role, source, relationship, confirmed_by_member_id, confirmed_at) values
  ${rows.join(',\n  ')}
on conflict (group_id, member_id) do nothing;
insert into public.page_posts (id, group_id, body, starts_at, location_id, lifecycle_state, discoverability) values
  (${q(postId(i, 1))}, ${q(gid(i))}, ${q(`Saturday at ${pg.name}: come along.`)}, date_trunc('day', now()) + interval '3 days 17 hours', ${q(lid(i))}, 'active', ${q(vis)}),
  (${q(postId(i, 2))}, ${q(gid(i))}, 'Thanks to everyone who came last week.', null, null, 'active', ${q(vis)})
on conflict (id) do nothing;
insert into public.items (id, member_id, kind, title, description, state, group_id)
values (${q(iid(i, 1))}, ${q(o)}, 'gathering', ${q(`${pg.name} meetup`)}, 'Come along.', 'published', ${q(gid(i))})
on conflict (id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values (${q(iid(i, 1))}, date_trunc('day', now()) + interval '5 days 18 hours')
on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select ${q(iid(i, 1))}, ${q(lid(i))}, 'one_time', 'approved'
 where not exists (select 1 from public.item_locations where item_id = ${q(iid(i, 1))});
insert into public.item_responses (item_id, responder_member_id, response_kind)
select v.item, v.who, 'rsvp' from (values (${q(iid(i, 1))}::uuid, ${q(rsvp)}::uuid), (${q(iid(i, 1))}::uuid, ${q(member)}::uuid)) v(item, who)
 where not exists (select 1 from public.item_responses r where r.item_id = v.item and r.responder_member_id = v.who);
`)
    if (pg.kind === 'business') {
      w(`insert into public.items (id, member_id, kind, title, description, brand_label, state, group_id) values
  (${q(iid(i, 2))}, ${q(o)}, 'product', 'Country sourdough loaf', 'Naturally leavened.', ${q(pg.name)}, 'published', ${q(gid(i))}),
  (${q(iid(i, 3))}, ${q(o)}, 'service', 'Bread-baking lesson', 'One hour, at the shop.', ${q(pg.name)}, 'published', ${q(gid(i))})
on conflict (id) do nothing;
insert into public.item_products (item_id, price_cents, price_unit) values (${q(iid(i, 2))}, 900, 'loaf') on conflict (item_id) do nothing;
insert into public.item_services (item_id, rate_model, rate_cents) values (${q(iid(i, 3))}, 'hourly', 4000) on conflict (item_id) do nothing;
insert into public.item_locations (item_id, location_id, schedule_kind, status)
select v.item, ${q(lid(i))}, v.kind, 'approved' from (values (${q(iid(i, 2))}::uuid, 'ongoing'), (${q(iid(i, 3))}::uuid, 'by_appointment')) v(item, kind)
 where not exists (select 1 from public.item_locations l where l.item_id = v.item);
insert into public.item_responses (item_id, responder_member_id, response_kind)
select ${q(iid(i, 2))}, ${q(rsvp)}, 'purchase'
 where not exists (select 1 from public.item_responses where item_id = ${q(iid(i, 2))} and responder_member_id = ${q(rsvp)});
`)
    }
  })

  const solo = (n: string) => `0d000000-0000-4000-8000-0000000099${n}`
  const business = people.find((p) => p.owns === 'business')!.id!
  w(`
-- 3. Things a member posted without a Page: /m/<handle>/{p,s,e}/...
insert into public.items (id, member_id, kind, title, description, state, group_id) values
  (${q(solo('01'))}, ${q(member)}, 'product', 'Jar of plum jam', 'From the backyard tree.', 'published', null),
  (${q(solo('02'))}, ${q(member)}, 'service', 'Bike tune-up', 'Bring it round.', 'published', null),
  (${q(solo('03'))}, ${q(member)}, 'gathering', 'Porch music night', 'Bring an instrument.', 'published', null)
on conflict (id) do nothing;
insert into public.item_products (item_id, price_cents, price_unit) values (${q(solo('01'))}, 600, 'jar') on conflict (item_id) do nothing;
insert into public.item_services (item_id, rate_model, rate_cents) values (${q(solo('02'))}, 'flat', 2500) on conflict (item_id) do nothing;
insert into public.item_gatherings (item_id, starts_at) values (${q(solo('03'))}, date_trunc('day', now()) + interval '4 days 19 hours')
on conflict (item_id) do nothing;

-- 4. Tags on every Page, and one report for the operator's queue.
insert into public.tags (id, label, normalized, status, created_by) values
  ('0f000000-0000-4000-8000-000000000001', 'Local food', 'qa-local-food', 'visible', ${q(business)}),
  ('0f000000-0000-4000-8000-000000000002', 'Weekend', 'qa-weekend', 'visible', ${q(business)})
on conflict do nothing;
insert into public.page_tags (group_id, tag_id)
select g.id, t.id from public.groups g, public.tags t
 where g.id::text like '0b000000-0000-4000-8000-%' and t.id::text like '0f000000-0000-4000-8000-00000000000%'
on conflict do nothing;
insert into public.reports (id, reporter_member_id, subject_kind, subject_id, body) values
  ('0f000000-0000-4000-8000-000000000101', ${q(persona('stranger').id!)}, 'group', ${q(gid(0))}, 'Seeded report for the operator queue.')
on conflict (id) do nothing;

commit;

refresh materialized view public.discoverable_items;
`)
  return out.join('')
}

function assertLocal(url: string | undefined): string {
  if (!url) throw new Error('DATABASE_URL is not set.')
  const host = new URL(url).hostname
  if (!LOCAL.has(host)) {
    console.error(`seed-personas: REFUSING ${host}. Personas carry a test password and go to a local stack only.`)
    process.exit(1)
  }
  return url
}

async function main() {
  const mode = process.argv[2]
  if (mode === '--generate') {
    writeFileSync(OUT, generate())
    console.log(`wrote ${OUT}`)
  } else if (mode === '--check') {
    if (readFileSync(OUT, 'utf8') !== generate()) {
      console.error('supabase/seeds/personas.sql is stale: run tsx scripts/seed-personas.ts --generate')
      process.exit(1)
    }
    console.log('personas.sql matches evals/personas.ts')
  } else if (mode === '--apply') {
    const url = assertLocal(process.env.DATABASE_URL)
    const client = new Client({ connectionString: url })
    await client.connect()
    try {
      await client.query(readFileSync(OUT, 'utf8'))
      console.log(`seeded ${PERSONAS.filter((p) => p.id).length} personas and ${PAGES.length} Pages`)
    } finally {
      await client.end()
    }
  } else {
    console.error('usage: tsx scripts/seed-personas.ts --generate | --check | --apply')
    process.exit(2)
  }
}

if (require.main === module) void main()
